### PR TITLE
fix : ignore the artifacts after make build

### PR DESCRIPTION
**Pull request by huahu0213**
Please answer these questions before submitting a pull request

- Why submit this pull request?
- [x] Bugfix
- [ ] New feature provided
- [ ] Improve performance
- [ ] Backport patches

- Related issues
ignore the artifacts after make build [#232](https://github.com/apache/apisix-ingress-controller/issues/232)
___
### Bugfix
- Description

- How to fix?
   The ./apisix-ingress-controller  changed to apisix-ingress-controller

### CODE REVIEW

**Comment by tokers** [comment]
@huahu0213 something not related with this PR were pushed.

**Comment by gxthrj** [comment]
Please keep the version feature in your `Branch_master_issue228` branch.

**Comment by huahu0213** [comment]
> Please keep the version feature in your `Branch_master_issue228` branch.

I'm sorry , it's my first time to submit the PR, not too skilled at this.  I will fixed it today and do better next time

**Comment by tokers** [comment]
> > Please keep the version feature in your `Branch_master_issue228` branch.
> 
> I'm sorry , it's my first time to submit the PR, not too skilled at this. I will fixed it today and do better next time

Feel free to ask any questions here, we'll help you :)

**Review by tokers — APPROVED** [review]

**Pull request merged**
