### PR TITLE
feat: support k8s native ingress and backend service in different…

### LINKED ISSUE #1374: feat: support k8s native ingress and backend service in the different namespace
```apiVersion: networking.k8s.io/v1
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    k8s.apisix.apache.org/svc-namespace: default
  name: details
  namespace: apisix
spec:
  ingressClassName: apisix
  rules:
  - host: bar.com
    http:
      paths:
      - backend:
          service:
            name: details
            port:
              number: 9080
        path: /
        pathType: Prefix
```
Like the example above, ingress is under the namespace apisix, and service details is under the default namespace.
In actual production, we did encounter such a scenario, which is to use the externalName type of Service that the nginx ingress controller can support. We now want to migrate to apisix and use the old ingress api. There is a problem with the externalName supported by the nginx ingress controller, that is, it will resolve the service of another namespace into clusterIp, which will cause the Layer 7 load balancing strategy to fail. So, it would be the best solution to get the endpoint of another namespace.

### PR DESCRIPTION
**Pull request by shareinto**
… namespace

### Type of change:

- [ ] Bugfix
- [x] New feature provided
- [ ] Improve performance
- [ ] Backport patches

### What this PR does / why we need it:
Resolves #1374 

### Pre-submission checklist:

* [x] Did you explain what problem does this PR solve? Or what new features have been added?
* [x] Have you added corresponding test cases?
* [ ] Have you modified the corresponding document?
* [ ] Is this PR backward compatible? **If it is not backward compatible, please discuss on the [mailing list](https://github.com/apache/apisix-ingress-controller#community) first**

### CODE REVIEW

**Comment by tao12345666333** [comment]
Thanks! Let me take a look.

**Comment by shareinto** [comment]
@tao12345666333 e2e test has passed,how can i rerun this,would you help please

**Review by lingsamuel — CHANGES_REQUESTED** [review]
Sorry for the late review, code LGTM, but PR needs to resolve the conflict. Thanks!

**Comment by lingsamuel** [comment]
@tao12345666333 PTAL

**Comment by tao12345666333** [comment]
yes! code LGTM.

Please resolve conflicts. Thanks!

**Review by lingsamuel — APPROVED** [review]

**Review by tao12345666333 — APPROVED** [review]
LGTM

**Pull request merged**
