### PR TITLE
fix: the fields in UpstreamPassiveHealthCheckUnhealthy should be timeouts

### PR DESCRIPTION
**Pull request by gxthrj**
Please answer these questions before submitting a pull request

- Why submit this pull request?
- [x] Bugfix
- [ ] New feature provided
- [ ] Improve performance
- [ ] Backport patches

- Related issues
https://github.com/apache/apisix-ingress-controller/issues/604

### CODE REVIEW

**Review by tokers — APPROVED** [review]

**Comment by tokers** [comment]
@gxthrj Add a test case to cover it?

**Comment by tao12345666333** [comment]
The changes are LGTM. 

Only one question: it's v1 stable version, should we bump the api-version?

**Comment by tokers** [comment]
> The changes are LGTM.
> 
> Only one question: it's v1 stable version, should we bump the api-version?

Agree +1, we may also generate a `v2alpha1` version.

**Comment by gxthrj** [comment]
But this is also a bug in the v1 version, and I think it needs to be fixed in the v1 version.

**Review by tao12345666333 — APPROVED** [review]

**Pull request merged**
