### PR TITLE
docs: broken links in markdown files

### PR DESCRIPTION
**Pull request by KishaniKandasamy**
Please answer these questions before submitting a pull request

- Why submit this pull request?
- [x] Bugfix
- [ ] New feature provided
- [ ] Improve performance
- [ ] Backport patches

- Related issues
fix: [#325](https://github.com/apache/apisix-website/issues/325)
___

### CODE REVIEW

**Comment by KishaniKandasamy** [comment]
Hi , for[ this broken link](https://apisix.apache.org/docs/ingress-controller/CRD-specification.md) , What could  be used to replace this?
Shall we use [this?](https://github.com/apache/apisix-ingress-controller/tree/master/samples/deploy/crd/v1beta1)

**Comment by tokers** [comment]
> Hi , for[ this broken link](https://apisix.apache.org/docs/ingress-controller/CRD-specification.md) , What could  be used to replace this?
> 
> 
> 
> 
> 
> Shall we use [this?](https://github.com/apache/apisix-ingress-controller/tree/master/samples/deploy/crd/v1beta1)

It was split into multiple documents.

**Comment by tokers** [comment]
> > Hi , for[ this broken link](https://apisix.apache.org/docs/ingress-controller/CRD-specification.md) , What could  be used to replace this?
> > 
> > 
> > 
> > 
> > 
> > Shall we use [this?](https://github.com/apache/apisix-ingress-controller/tree/master/samples/deploy/crd/v1beta1)
> 
> It was split into multiple documents.

It was in docs/latest/en/concepts.

**Comment by KishaniKandasamy** [comment]
> > > Hi , for[ this broken link](https://apisix.apache.org/docs/ingress-controller/CRD-specification.md) , What could  be used to replace this?
> > > 
> > > Shall we use [this?](https://github.com/apache/apisix-ingress-controller/tree/master/samples/deploy/crd/v1beta1)
> > 
> > 
> > It was split into multiple documents.
> 
> It was in docs/latest/en/concepts.

yes ,So  for resources, Shall we add https://github.com/apache/apisix-ingress-controller/tree/master/docs/en/latest/concepts?

**Comment by tokers** [comment]
> > > > Hi , for[ this broken link](https://apisix.apache.org/docs/ingress-controller/CRD-specification.md) , What could  be used to replace this?
> > > > 
> > > > Shall we use [this?](https://github.com/apache/apisix-ingress-controller/tree/master/samples/deploy/crd/v1beta1)
> > > 
> > > 
> > > It was split into multiple documents.
> > 
> > 
> > It was in docs/latest/en/concepts.
> 
> yes ,So for resources, Shall we add https://github.com/apache/apisix-ingress-controller/tree/master/docs/en/latest/concepts?

Yep.

**Review by tokers — APPROVED** [review]

**Pull request merged**
