### PR TITLE
feat: multiple controllers handle different ApisixRoute CRDs

### PR DESCRIPTION
**Pull request by Gallardot**
Signed-off-by: Gallardot <tttick@163.com>

Close https://github.com/apache/apisix-ingress-controller/issues/592

### Type of change:

- [ ] Bugfix
- [x] New feature provided
- [ ] Improve performance
- [ ] Backport patches

### Pre-submission checklist:

* [ ] Did you explain what problem does this PR solve? Or what new features have been added?
* [ ] Have you added corresponding test cases?
* [ ] Have you modified the corresponding document?
* [x] Is this PR backward compatible? **If it is not backward compatible, please discuss on the [mailing list](https://github.com/apache/apisix-ingress-controller#community) first**

### CODE REVIEW

**Comment by Gallardot** [comment]
I think this PR is ready for review. But there are some field naming issues that I think need to be discussed together.

1.  Is the new `instance-id` configuration appropriate?  The `ingress_class` configuration is not reused mainly to avoid version incompatibility. Reduce the cost of enabling this feature from inventory projects and reduce the hassle of version upgrades.

2. New `IngressClass` field in ApisixRoute object. Is this name appropriate? How about `gatewayclass`?

@tao12345666333 @AlinsRan @lingsamuel  @tokers  WDYT?

**Comment by tao12345666333** [comment]
Thanks for your contributions. 
I will back tomorrow after some thinking 🤔

**Comment by AlinsRan** [comment]
I think it depends on CRDs roadmap. But its evolution is not clear at present.
Maybe we can use annotations to temporarily transition. similar to ingress resource.

**Comment by AlinsRan** [comment]
@tao12345666333  @lingsamuel @Gallardot  WDYT?

**Comment by tao12345666333** [comment]
Sorry for the delay.  

I think using `IngressClass` is enough. [1]
In the resources of the Gateway API specification, there is `GatewayClass`, which allows for the definition of a controller name[2] to distinguish between different controllers.


So

- Using `controller-name`  instead of `instance-id`.   It already exists, make it configurable. https://github.com/apache/apisix-ingress-controller/blob/4241b673b3fd385e82d5ca3a39fed8acafa5bd64/pkg/config/config.go#L59-L61

- The `ingressClass` field is a good fit. We can reuse the IngressClass resource directly, and it is easier to integrate with existing tools or users' existing configuration.  No other resources need to be introduced.



1: https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-class
2: https://gateway-api.sigs.k8s.io/api-types/gatewayclass/#gatewayclass-controller-selection

**Comment by lingsamuel** [comment]
ID is more like an auto generated string, but here it should be defined by the user. I agree with @tao12345666333

**Pull request closed without merging**
