### PR TITLE
add chinese version of decument

### LINKED ISSUE #278: docs: add chinese version  of ducument
add  chinese version  of ducument

### PR DESCRIPTION
**Pull request by soulsoul**
Please answer these questions before submitting a pull request

- Why submit this pull request?
- [ ] Bugfix
- [ ] New feature provided
- [ ] Improve performance
- [ ] Backport patches
- [ * ] improve the document

Resolves #278

### CODE REVIEW

**Comment by membphis** [comment]
@soulsoul pls take a look at the output of CI

image

**Comment by membphis** [comment]
@soulsoul this pr is big, and I think you can split it into multiple small PRs. it is easier to review and merge.

**Comment by gxthrj** [comment]
Thanks, but we don’t want us to maintain Chinese documents all the time, This will increase a lot of maintenance costs.
What other peoples think?

**Comment by gxthrj** [comment]
Close this stale PR, feel free to reopen.

**Pull request closed without merging**
