### PR TITLE
docs: update "FAQ" page

### PR DESCRIPTION
**Pull request by navendu-pottekkat**
Signed-off-by: Navendu Pottekkat <navendu@apache.org>

Updated the FAQ page docs.

### CODE REVIEW

**Comment by navendu-pottekkat** [comment]
Trailing punctuation of ? should be allowed in headings as FAQ pages will have them.

**Review by juzhiyuan — APPROVED** [review]
LGTM

**Review by tao12345666333 — COMMENTED** [review]
please fix lint error. thanks

**Comment by navendu-pottekkat** [comment]
@tao12345666333 So I updated the version of the `markdownlint` tool. That seems to fix the issue.

**Review by tao12345666333 — APPROVED** [review]

**Pull request merged**
