### PR TITLE
fix: controller err handler should ignore not found error

### PR DESCRIPTION
**Pull request by lingsamuel**
Signed-off-by: Ling Samuel <lingsamuelgrace@gmail.com>

### Type of change:

- [x] Bugfix

### What this PR does / why we need it:
Fixes: #810

### CODE REVIEW

**Review by tao12345666333 — APPROVED** [review]
LGTM

**Review by gxthrj — APPROVED** [review]
LGTM， should ignore the NOT FOUND error.

**Comment by tao12345666333** [comment]
Please resolve conflicts. Thanks!  @lingsamuel

**Comment by lingsamuel** [comment]
@tao12345666333 done

**Pull request merged**
