### PR TITLE
add ldap-auth authorization method

### PR DESCRIPTION
**Pull request by machinly**
### Type of change:

- [ ] Bugfix
- [X] New feature provided
- [ ] Improve performance
- [ ] Backport patches

### What this PR does / why we need it:
This PR add add ldap-auth support on ApisixConsumer and ApisixRoute CRD.
It's for issue #1574.

### Pre-submission checklist:

* [ ] Did you explain what problem does this PR solve? Or what new features have been added?
* [X] Have you added corresponding test cases?
* [ ] Have you modified the corresponding document?
* [ ] Is this PR backward compatible? **If it is not backward compatible, please discuss on the [mailing list](https://github.com/apache/apisix-ingress-controller#community) first**

### CODE REVIEW

**Review by tao12345666333 — COMMENTED** [review]
LGTM

Just remove some modifications related to v2beta3.

**Comment by tao12345666333** [comment]
@AlinsRan @lingsamuel  PTAL

**Comment by machinly** [comment]
> LGTM
> 
> Just remove some modifications related to v2beta3.

Thanks for the review. I'm completed removing ldap-auth support for v2beta3.

**Review by tao12345666333 — APPROVED** [review]
I did a quick review, LTM

**Review by lingsamuel — APPROVED** [review]

**Pull request merged**
