### PR TITLE
feat: support environment variable in config file

### PR DESCRIPTION
**Pull request by nic-6443**
Sorry, the https://github.com/apache/apisix-ingress-controller/pull/713 closed because I wrongly rebase the upstream code, so now I have initiated a new PR. e2e has been added, can be review again

Please answer these questions before submitting a pull request

- Why submit this pull request?
- [ ] Bugfix
- [x] New feature provided
- [ ] Improve performance
- [ ] Backport patches

- Related issues
#710

### CODE REVIEW

**Comment by nic-6443** [comment]
@tao12345666333

**Comment by tao12345666333** [comment]
Please resolve the conflicts, thanks!

**Comment by tao12345666333** [comment]
The code LGTM. Thanks!

But I personally prefer to directly support configuration through environment variables or through configuration files
Instead of supporting environment variables in the configuration file.

WDYT? @gxthrj @tokers @lilien1010

**Comment by nic-6443** [comment]
> The code LGTM. Thanks!
> 
> But I personally prefer to directly support configuration through environment variables or through configuration files Instead of supporting environment variables in the configuration file.
> 
> WDYT? @gxthrj @tokers @lilien1010
In the case that the user chooses to use file configuration instead of commands of container, the use of environment variables is to write sensitive information through downward api and secret.  So if the program directly uses env, we need to consider the problem of file configuration and env configuration merging,  doesn't make this problem easy.

**Comment by tokers** [comment]
> The code LGTM. Thanks!
> 
> But I personally prefer to directly support configuration through environment variables or through configuration files Instead of supporting environment variables in the configuration file.
> 
> WDYT? @gxthrj @tokers @lilien1010

Softwares like ETCD and Istio support using environment variables directly, and the precedence is highest, so it's my understanding that we do should support environment variables, configuration file and command line options.

**Comment by nic-6443** [comment]
@tao12345666333 @tokers
Should we merge the current feature first, and add more options later?

**Comment by tokers** [comment]
> @tao12345666333 @tokers Should we merge the current feature first, and add more options later?

Agree, or this PR might be too large to review.

**Review by tao12345666333 — APPROVED** [review]

**Comment by tao12345666333** [comment]
Let's move forward, this feature also has some usage scenarios.

**Comment by tao12345666333** [comment]
ping @gxthrj @tokers  for review & merge.

**Review by lilien1010 — APPROVED** [review]
🎉

**Review by tokers — APPROVED** [review]

**Review by lingsamuel — APPROVED** [review]

**Pull request merged**
