### PR TITLE
fix: golang:1.19 base image vulnerability

### PR DESCRIPTION
**Pull request by fengshunli**
Signed-off-by: fengshunli <1171313930@qq.com>

### Type of change:

- [ ] Bugfix
- [ ] New feature provided
- [ ] Improve performance
- [ ] Backport patches

### Pre-submission checklist:

* [ ] Did you explain what problem does this PR solve? Or what new features have been added?
* [ ] Have you added corresponding test cases?
* [ ] Have you modified the corresponding document?
* [ ] Is this PR backward compatible? **If it is not backward compatible, please discuss on the [mailing list](https://github.com/apache/apisix-ingress-controller#community) first**

### CODE REVIEW

**Review by tao12345666333 — CHANGES_REQUESTED** [review]
I don't see any reason for this PR to be needed.

**Comment by fengshunli** [comment]
golang:1.19 image has many high-risk vulnerabilities and security risks. It is recommended to switch to golang:1.19-alpine3.17
image

**Comment by tao12345666333** [comment]
It is only used during the build phase, not the final image.

**Comment by fengshunli** [comment]
there are also many high-risk vulnerabilities in centos, for details, refer to https://github.com/apache/apisix-ingress-controller/issues/1649

**Pull request closed without merging**
