### PR TITLE
fix: filter useless pod update event

### PR DESCRIPTION
**Pull request by cmssczy**
### Type of change:

- [x] Bugfix
- [ ] New feature provided
- [ ] Improve performance
- [ ] Backport patches

### What this PR does / why we need it:

`onUpdate` will get pod update event every `resync_interval` seconds/hours. It's unnecessary.

### Pre-submission checklist:

* [ ] Did you explain what problem does this PR solve? Or what new features have been added?
* [ ] Have you added corresponding test cases?
* [ ] Have you modified the corresponding document?
* [ ] Is this PR backward compatible? **If it is not backward compatible, please discuss on the [mailing list](https://github.com/apache/apisix-ingress-controller#community) first**

### CODE REVIEW

**Comment by tao12345666333** [comment]
Flaky test https://github.com/apache/apisix-ingress-controller/issues/869

**Review by gxthrj — COMMENTED** [review]
The logic is OK.

**Review by lingsamuel — APPROVED** [review]

**Comment by lingsamuel** [comment]
@gxthrj It seems that what you submitted is not an approval, but just a comment.

**Review by tao12345666333 — APPROVED** [review]
LGTM

re-run CI test.

**Comment by cmssczy** [comment]
Similar error as before. Nothing to with this pr. @tao12345666333

**Comment by tao12345666333** [comment]
Yep. Flaky test https://github.com/apache/apisix-ingress-controller/issues/869
This issue has not yet been reproduced locally. re-run :crying_cat_face:

**Comment by tao12345666333** [comment]
It's green

**Pull request merged**
