### PR TITLE
fix: CRD v1 preserve unknown fields

### PR DESCRIPTION
**Pull request by tao12345666333**
Signed-off-by: Jintao Zhang <zhangjintao9020@gmail.com>

Please answer these questions before submitting a pull request

- Why submit this pull request?
- [x] Bugfix
- [ ] New feature provided
- [ ] Improve performance
- [ ] Backport patches

- Related issues

___
### Bugfix
- Description

fix: CRD v1 preserve unknown fields

- How to fix?

___
### New feature or improvement
- Describe the details and related test reports.

___
### Backport patches
- Why need to backport?

- Source branch

- Related commits and pull requests

- Target branch

### CODE REVIEW

**Review by gxthrj — APPROVED** [review]

**Comment by tao12345666333** [comment]
Wait for review @apache/apisix-committers  PTAL!
Thanks!

**Comment by moonming** [comment]
@tao12345666333 please do not ping a group of committer. Someone once pinged all the committers of the Apache Foundation by mistake

**Comment by tao12345666333** [comment]
@moonming  Got it! Since this is a serious bug and many people are on vacation, I hope someone else can help review and quickly complete this fix.

**Review by moonming — APPROVED** [review]

**Comment by tao12345666333** [comment]
#698 is ready, it already contains this change.

I suggest to merge it directly.

**Review by nic-chen — APPROVED** [review]

**Review by tokers — APPROVED** [review]

**Pull request merged**
