### PR TITLE
Chore:   upgrade CI  ginkgo 1.9.0 to 1.9.2

### PR DESCRIPTION
**Pull request by WVenus**
### Type of change:
- [x] Chore

### What this PR does / why we need it:

 upgrade CI  ginkgo 1.9.0 to 1.9.2，reference (#1799)

### CODE REVIEW

**Comment by basefas** [comment]
also need to change in makefile，ginkgo-check

**Review by Gallardot — APPROVED** [review]
LGTM. Thank you for your contribution.

**Review by tao12345666333 — APPROVED** [review]
LGTM

**Comment by Qizeng-api7** [comment]
Hello @WVenus! I am the operator of the APISIX Community. Thank you for your contribution to Apache APISIX! To express our gratitude and encouragement for your contribution, the Apache APISIX community would like to present to you the APISIX Contributor Certificate! However, we couldn't find your email address on your GitHub page, would you mind letting us know? We will send you a digital certificate by email later as a token of our appreciation.

**Pull request merged**
