### PR TITLE
feat: add support for filter_func for ApisixRoute

### PR DESCRIPTION
**Pull request by aynp**
### Type of change:
- [ ] Bugfix
- [x] New feature provided
- [ ] Improve performance
- [ ] Backport patches

### What this PR does / why we need it:
close: #1532

Add support for `filter_func` for ApisixRoute

### CODE REVIEW

**Comment by tao12345666333** [comment]
Thanks!

**Comment by tao12345666333** [comment]
Please add e2e test case to cover this one.
And resolve conflicts, thanks

**Comment by tao12345666333** [comment]
Please resolve conflicts. Thanks!

**Comment by tao12345666333** [comment]
LGTM

**Review by tao12345666333 — APPROVED** [review]

**Review by AlinsRan — APPROVED** [review]

**Pull request merged**
