### PR TITLE
chore:ingress supports service mode

### PR DESCRIPTION
**Pull request by ab61636452**
### Type of change:

- [ ] Bugfix
- [x] New feature provided
- [ ] Improve performance
- [ ] Backport patches
- [ ] Documentation
- [ ] Refactor
- [ ] Chore
- [ ] CI/CD or Tests

### Pre-submission checklist:

- [ ] Did you explain what problem does this PR solve? Or what new features have been added?
- [ ] Have you added corresponding test cases?
- [ ] Have you modified the corresponding document?
- [x] Is this PR backward compatible? **If it is not backward compatible, please discuss on the [mailing list](https://github.com/apache/apisix-ingress-controller#community) first**

### CODE REVIEW

**Comment by ab61636452** [comment]
backward compatibility

**Comment by ab61636452** [comment]
ingress When generating the Upstream, the service mode is supported

**Comment by ab61636452** [comment]
为什么没有反应？

**Comment by ab61636452** [comment]
Why no one to deal with it

**Comment by olexiyb** [comment]
This is important to have in order as the only way to use apisix in existing helm charts requires to set `resolveGranularity: service`
Related to https://github.com/apache/apisix/issues/8947

**Pull request closed without merging**
