### PR TITLE
chore: Make docker compose and docker-compose compatible

### PR DESCRIPTION
**Pull request by Chever-John**
### Type of change:

- [ ] Bugfix
- [ ] New feature provided
- [ ] Improve performance
- [ ] Backport patches
- [ ] Documentation
- [ ] Refactor
- [ ] Chore
- [x] CI/CD or Tests

### What this PR does / why we need it:

This PR makes `docker-compose` and `docker compose` compatible. The source issue(#1201) is this. 
This PR will solve the problem of `docker-compose` not being found when doing the e2e-test locally.

### Pre-submission checklist:

- [ ] Did you explain what problem does this PR solve? Or what new features have been added?
- [ ] Have you added corresponding test cases?
- [ ] Have you modified the corresponding document?
- [ ] Is this PR backward compatible? **If it is not backward compatible, please discuss on the [mailing list](https://github.com/apache/apisix-ingress-controller#community) first**

### CODE REVIEW

**Comment by Chever-John** [comment]
Hi, can anyone permit me to run ci for this PR?
@tao12345666333 @AlinsRan

**Comment by tao12345666333** [comment]
Done

**Review by Gallardot — APPROVED** [review]
LGTM

**Review by tao12345666333 — APPROVED** [review]
LGTM

**Pull request merged**
