### PR TITLE
chore: optimize log message when the endpoint does not have a corresponding service

### PR DESCRIPTION
**Pull request by lingsamuel**
- Why submit this pull request?
- [ ] Bugfix
- [ ] New feature provided
- [ ] Improve performance
- [ ] Backport patches

- Related issues

___
### Bugfix
- Description

- How to fix?

___
### New feature or improvement
- Some endpoints doesn't have corresponding services, currently endpoint controller will log massive warning continuously

### CODE REVIEW

**Comment by lingsamuel** [comment]
@tokers

**Review by tokers — APPROVED** [review]

**Comment by tokers** [comment]
@lingsamuel The documentation changes are not related with the purpose of this PR. One PR resolves one thing.

**Comment by lingsamuel** [comment]
Mistake branch :joy:

**Review by gxthrj — APPROVED** [review]

**Comment by lingsamuel** [comment]
Actions failed to start due to [GitHub incidents](https://www.githubstatus.com/incidents/m16jzl31gnqt)

**Pull request merged**
