### PR TITLE
chore: add Apache License header in each go source file.

### PR DESCRIPTION
**Pull request by tokers**
Files are filtered by:

```shell
find . -name "*.go"
```

### CODE REVIEW

**Comment by tokers** [comment]
@membphis @moonming @gxthrj Please take a look.

**Review by moonming — COMMENTED** [review]
LGTM
and we need add CI to check ASF header later.

**Review by moonming — APPROVED** [review]

**Comment by moonming** [comment]
@Firstsawyou please add CI check for ASF header.

**Comment by gxthrj** [comment]
Related to #38 , only golang files in this PR

**Pull request merged**
