### PR TITLE
fix: sync resource after namespace changed

### PR DESCRIPTION
**Pull request by bigfish02**
### Type of change:

- [x ] Bugfix
- [ ] New feature provided
- [ ] Improve performance
- [ ] Backport patches
- [ ] Documentation
- [ ] Refactor
- [ ] Chore
- [ ] CI/CD or Tests

### What this PR does / why we need it:

I deploy apisix with namespace_selector option. If I apply apisixroute in a namespace, and then label with that namespace. It does not work.

Example:

1. deploy apisix with namespace_selector option
```
kubernetes:
  namespace_selector:
  - apisix=true
 ```

2. deploy apisixroute
```
kubectl create ns test
kubectl apply -f  -  <<EOF
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: nginx
  namespace: test
spec:
  http:
  - backends:
    - serviceName: nginx
      servicePort: 80
    match:
      hosts:
      - xx.com
      paths:
      - /*
    name: nginx
EOF
kubectl label ns test apisix=true
```
apisix-ingress-controller does not sync that apisixroute after I label that namespace.

### CODE REVIEW

**Review by tao12345666333 — COMMENTED** [review]
Thank you for your contribution. Could you please add an e2e test case to cover it?

**Comment by bigfish02** [comment]
> Thank you for your contribution. Could you please add an e2e test case to cover it?

no problem，i will add it later

**Comment by lingsamuel** [comment]
the code LGTM. We can merge this once the e2e tests are added

**Review by lingsamuel — APPROVED** [review]

**Review by tao12345666333 — APPROVED** [review]
LGTM

**Pull request merged**
