### PR TITLE
Chore: Upgrade Go tool chain version 1.19 to version 1.20 

### PR DESCRIPTION
**Pull request by WVenus**
### Type of change:

- [x] Chore

### What this PR does / why we need it:

Upgrade Go tool chain version 1.19 to version 1.20, reference (#1786)

### Pre-submission checklist:

- [ ] Did you explain what problem does this PR solve? Or what new features have been added?
- [ ] Have you added corresponding test cases?
- [ ] Have you modified the corresponding document?
- [ ] Is this PR backward compatible? **If it is not backward compatible, please discuss on the [mailing list](https://github.com/apache/apisix-ingress-controller#community) first**

### CODE REVIEW

**Review by Gallardot — COMMENTED** [review]
LGTM.  

At the same time, the [Installed Go 1.19 or later](https://github.com/apache/apisix-ingress-controller/blob/master/docs/en/latest/contribute.md#prerequisites) in the document needs to be updated.

**Comment by Gallardot** [comment]
@WVenus 
Thank you for your contribution. 
Notice that CI failed. I've retried the failed job, but it still doesn't work. Before merging, you need to fix CI. Thank you.

**Comment by tao12345666333** [comment]
I checked the errors in CI, all of which were caused by the failure to start the coredns pod. 

```
 [FAILED] in [It] - /home/runner/work/apisix-ingress-controller/apisix-ingress-controller/test/e2e/suite-ingress/suite-ingress-resource/stream.go:143 @ 04/14/23 02:31:51.863
  Dumping namespace contents
  NAME                                                            READY   UP-TO-DATE   AVAILABLE   AGE
  deployment.apps/apisix-deployment-e2e-test                      1/1     1            1           33s
  deployment.apps/coredns                                         0/1     1            0           6s
  deployment.apps/etcd-deployment-e2e-test                        1/1     1            1           38s
  deployment.apps/httpbin-deployment-e2e-test                     1/1     1            1           28s
  deployment.apps/ingress-apisix-controller-deployment-e2e-test   1/1     1            1           22s
  deployment.apps/test-backend-deployment-e2e-test                1/1     1            1           26s
```

**Review by tao12345666333 — APPROVED** [review]

**Review by lingsamuel — APPROVED** [review]

**Review by lingsamuel — APPROVED** [review]

**Comment by tao12345666333** [comment]
The failed test case is unrelated to this modification, I will merge it. Thank you.
```

  [FAILED] 
  	Error Trace:	/home/runner/work/apisix-ingress-controller/apisix-ingress-controller/test/e2e/suite-ingress/suite-ingress-resource/stream.go:143
  	            				/home/runner/go/pkg/mod/github.com/onsi/ginkgo/v2@v2.9.5/internal/node.go:463
  	            				/home/runner/go/pkg/mod/github.com/onsi/ginkgo/v2@v2.9.5/internal/suite.go:863
  	            				/opt/hostedtoolcache/go/1.20.6/x64/src/runtime/asm_amd64.s:1598
  	Error:      	Expected nil, but got: &net.DNSError{Err:"read udp [::1]:34936->[::1]:31846: read: connection refused", Name:"httpbin.org", Server:"127.0.0.53:53", IsTimeout:false, IsTemporary:true, IsNotFound:false}
  	Test:       	suite-ingress-resource: ApisixRoute stream Testing suite-ingress-resource: scaffold v2 stream udp proxy
  	Messages:   	dns query error
  
  In [It] at: /home/runner/work/apisix-ingress-controller/apisix-ingress-controller/test/e2e/suite-ingress/suite-ingress-resource/stream.go:143 @ 08/04/23 01:15:58.675

  Full Stack Trace
    github.com/apache/apisix-ingress-controller/test/e2e/suite-ingress/suite-ingress-resource.glob..func10.1.2()
    	/home/runner/work/apisix-ingress-controller/apisix-ingress-controller/test/e2e/suite-ingress/suite-ingress-resource/stream.go:143 +0x537

  There were additional failures detected.  To view them in detail run ginkgo -vv
```

**Pull request merged**
