### PR TITLE
fix docs group version

### PR DESCRIPTION
**Pull request by misstick86**
Signed-off-by: Song Wu <uxiaosongsong@gmail.com>

### Type of change:

- [ ] Bugfix

### What this PR does / why we need it:

the new Group version about apisix is `apisix.apache.org/v2beta3`, but still use `apisix.apache.org/v2` in docs. 
so  in order to correct the problem I submit a pr t fix it.

### CODE REVIEW

**Comment by AlinsRan** [comment]
The new version of crd is v2, and v2beta3 will be discarded soon.
https://github.com/apache/apisix-ingress-controller/issues/1179

**Comment by misstick86** [comment]
yeah. I see.

**Comment by tao12345666333** [comment]
#1338 

we are now in v1.5.0 release window, please see #1351 for detail.

thanks!

**Comment by misstick86** [comment]
@tao12345666333  thank you.  I noticed taht.

**Comment by tao12345666333** [comment]
I will close this one

**Pull request closed without merging**
