### PR TITLE
chore: upgrade apiVersion from v2beta1 to v2beta3

### PR DESCRIPTION
**Pull request by Belyenochi**
### Type of change:

- [x] Bugfix
- [ ] New feature provided
- [ ] Improve performance
- [ ] Backport patches

### What this PR does / why we need it:
Resolved [#915](https://github.com/apache/apisix-ingress-controller/issues/915)

### CODE REVIEW

**Comment by Belyenochi** [comment]
@tao12345666333 @lingsamuel help merge.

**Comment by tao12345666333** [comment]
Thanks!

Can you update the rest of the docs about `v2beta1` as well?

* docs/en/latest/practices/mtls/route.yaml
* docs/en/latest/practices/check-crd-status.md
* docs/en/latest/practices/mtls.md
* docs/en/latest/practices/manage-certificates-with-cert-manager.md
* docs/en/latest/references/apisix_route_v2beta1.md

**Comment by Belyenochi** [comment]
> Thanks!
> 
> Can you update the rest of the docs about `v2beta1` as well?
> 
> * docs/en/latest/practices/mtls/route.yaml
> * docs/en/latest/practices/check-crd-status.md
> * docs/en/latest/practices/mtls.md
> * docs/en/latest/practices/manage-certificates-with-cert-manager.md
> * docs/en/latest/references/apisix_route_v2beta1.md

OK, I will.

**Comment by Belyenochi** [comment]
> Thanks!
> 
> Can you update the rest of the docs about `v2beta1` as well?
> 
> * docs/en/latest/practices/mtls/route.yaml
> * docs/en/latest/practices/check-crd-status.md
> * docs/en/latest/practices/mtls.md
> * docs/en/latest/practices/manage-certificates-with-cert-manager.md
> * docs/en/latest/references/apisix_route_v2beta1.md

Done

**Review by lingsamuel — APPROVED** [review]

**Pull request merged**
