### PR TITLE
feat: support nginx vars in ApisixRoute v2alpha1

### PR DESCRIPTION
**Pull request by tokers**
Please answer these questions before submitting a pull request

- Why submit this pull request?
- [ ] Bugfix
- [x] New feature provided
- [ ] Improve performance
- [ ] Backport patches

- Related issues

#302 

- Features

This Pull Request aims at exposing the `nginxVars` field in ApisixRoute/v2alpha1, the apisix-ingress-controller will translate the `nginxVars` to `vars` in Route.

### CODE REVIEW

**Comment by gxthrj** [comment]
Need docs for the usage of ` nginxVars`.

**Comment by tokers** [comment]
@gxthrj Please take a look when you have time.

**Review by gxthrj — APPROVED** [review]

**Comment by oldthreefeng** [comment]
这个对应的是 route里面的 这个vars变量吧.  我没理解错吧. 
```
  "vars": [
    [
      "scheme",    => subject
      "==",           => op
      "http"          => value
    ]
  ],
```

**Comment by gxthrj** [comment]
> 这个对应的是 route里面的 这个vars变量吧. 我没理解错吧.
> 
> ```
>   "vars": [
>     [
>       "scheme",    => subject
>       "==",           => op
>       "http"          => value
>     ]
>   ],
> ```

Right！

**Pull request merged**
