### PR TITLE
feat: add golangci-lint

### PR DESCRIPTION
**Pull request by batman-ezio**
Please answer these questions before submitting a pull request

- Why submit this pull request?
- [ ] Bugfix
- [x] New feature provided
- [ ] Improve performance
- [ ] Backport patches

- Related issues

___
### Bugfix
- Description

- How to fix?

___
### New feature or improvement
- add golangci-lint to github actions https://github.com/marketplace/actions/run-golangci-lint

___
### Backport patches
- Why need to backport?

- Source branch

- #367 

- Target branch

### CODE REVIEW

**Comment by batman-ezio** [comment]
@tokers  after setup , I see there's some errors in actions,  may need some permission settings
image

**Comment by tokers** [comment]
> @tokers after setup , I see there's some errors in actions, may need some permission settings
> image

Sigh, Only official or Apache itself's actions are allowed to use for now. You may try to download golangci-lint and execute in shell.

**Comment by tokers** [comment]
@batman-ezio Refer to https://github.com/apache/apisix-dashboard/blob/master/.github/workflows/go-lint.yml for some details.

**Comment by Yiyiyimu** [comment]
@batman-ezio Or you could try to add the action repo as a submodule, recursively checkout, and then use it as the Action source. See [Apache Recommended Way](https://cwiki.apache.org/confluence/display/BUILDS/GitHub+Actions+status#GitHubActionsstatus-Security)

**Comment by tokers** [comment]
@batman-ezio Hi, it seems that you don't actually run the `make lint` command but just installing the golangci-lint.

**Comment by tokers** [comment]
Solved by another PR #419 , now closing it.

**Pull request closed without merging**
