### PR TITLE
chore: Upgrade to APISIX v2.14.1

### PR DESCRIPTION
**Pull request by tao12345666333**
Signed-off-by: Jintao Zhang <zhangjintao9020@gmail.com>

### Type of change:

- [x] Bugfix
- [ ] New feature provided
- [ ] Improve performance
- [ ] Backport patches

### Pre-submission checklist:

* [ ] Did you explain what problem does this PR solve? Or what new features have been added?
* [ ] Have you added corresponding test cases?
* [ ] Have you modified the corresponding document?
* [ ] Is this PR backward compatible? **If it is not backward compatible, please discuss on the [mailing list](https://github.com/apache/apisix-ingress-controller#community) first**

### CODE REVIEW

**Review by tokers — APPROVED** [review]

**Review by juzhiyuan — APPROVED** [review]

**Comment by juzhiyuan** [comment]
Hi @tao12345666333, is this PR related to CI failure?

**Comment by tao12345666333** [comment]
https://github.com/apache/apisix-ingress-controller/runs/6744951674?check_suite_focus=true#step:3:9673

```
  	            		Error:      	
  	            		            	expected string equal to:
  	            		            	 "https://httpbin.org/sample"
  	            		            	but got:
  	            		            	 "https://httpbin.org:9443/sample"
  	Test:       	suite-annotations: redirect annotations redirect http-to-https in ingress networking/v1
```

It might be related to the following issue
* https://github.com/apache/apisix/issues/7172
* https://github.com/apache/apisix/issues/7003
* https://github.com/apache/apisix/issues/4942

I will not merge this PR until the CI jobs are passed

**Comment by tao12345666333** [comment]
```
    127.0.0.1 - - [06/Jun/2022:02:56:06 +0000] localhost:31234 "GET /apisix/admin/routes HTTP/1.1" 200 592 0.005 "-" "Go-http-client/1.1" - - - "http://localhost:31234"
    2022/06/06 02:56:09 [warn] 45#45: *1629 [lua] hmac-auth.lua:452: phase_func(): client request can't be validated: access key or signature missing, client: 127.0.0.1, server: _, request: "GET /ip HTTP/1.1", host: "httpbin.org"
    2022/06/06 02:56:09 [warn] 45#45: *1629 [lua] plugin.lua:750: run_plugin(): hmac-auth exits with http status code 401, client: 127.0.0.1, server: _, request: "GET /ip HTTP/1.1", host: "httpbin.org"
```


```
    2022-06-06T10:55:58+08:00	debug	apisix/route.go:160	creating route	{"body": "{\"id\":\"35852e3a\",\"name\":\"ingress-apisix-e2e-tests-default-169142018_httpbin-route_rule1\",\"desc\":\"Created by apisix-ingress-controller, DO NOT modify it manually\",\"labels\":{\"managed-by\":\"apisix-ingress-controller\"},\"hosts\":[\"httpbin.org\"],\"vars\":[[\"http_x_foo\",\"==\",\"bar\"]],\"uris\":[\"/ip\"],\"upstream_id\":\"bd4e6ae4\",\"plugins\":{\"hmac-auth\":{}}}", "url": "http://apisix-service-e2e-test:9180/apisix/admin/routes/35852e3a"}
    2022-06-06T10:55:58+08:00	debug	apisix/resource.go:93	got route: {"vars":[["http_x_foo","==","bar"]],"upstream_id":"bd4e6ae4","labels":{"managed-by":"apisix-ingress-controller"},"update_time":1654484158,"create_time":1654484158,"priority":0,"name":"ingress-apisix-e2e-tests-default-169142018_httpbin-route_rule1","plugins":{"hmac-auth":{}},"status":1,"hosts":["httpbin.org"],"id":"35852e3a","desc":"Created by apisix-ingress-controller, DO NOT modify it manually","uris":["\/ip"]}
    2022-06-06T10:55:58+08:00	error	ingress/status.go:339	unsupported resource record: &{{ } {httpbin-route  ingress-apisix-e2e-tests-default-169142018  8430e99b-6a87-4f1c-bca6-a3765f2201c1 4397 %!s(int64=1) 2022-06-06 10:55:58 +0800 HKT <nil> %!s(*int64=<nil>) map[] map[kubectl.kubernetes.io/last-applied-configuration:{"apiVersion":"apisix.apache.org/v2beta3","kind":"ApisixRoute","metadata":{"annotations":{},"name":"httpbin-route","namespace":"ingress-apisix-e2e-tests-default-169142018"},"spec":{"http":[{"authentication":{"enable":true,"type":"hmacAuth"},"backends":[{"serviceName":"httpbin-service-e2e-test","servicePort":80}],"match":{"exprs":[{"op":"Equal","subject":{"name":"X-Foo","scope":"Header"},"value":"bar"}],"hosts":["httpbin.org"],"paths":["/ip"]},"name":"rule1"}]}}
    ] [] []  [{kubectl-client-side-apply Update apisix.apache.org/v2beta3 2022-06-06 10:55:58 +0800 HKT FieldsV1 {"f:metadata":{"f:annotations":{".":{},"f:kubectl.kubernetes.io/last-applied-configuration":{}}},"f:spec":{".":{},"f:http":{}}} }]} {[{rule1 %!s(int=0) %!s(*v2.UpstreamTimeout=<nil>) {[/ip] [] [httpbin.org] [] [{{Header X-Foo} Equal [] %!s(*string=0xc0005a4210)}]} [{httpbin-service-e2e-test {%!s(intstr.Type=0) %!s(int32=80) }  %!s(*int=<nil>) }] %!s(bool=false)  [] {%!s(bool=true) hmacAuth {} {  }}}] []} {[]}}
    2022-06-06T10:56:00+08:00	debug	ingress/controller.go:766	success check health for default cluster
    2022-06-06T10:56:05+08:00	debug	ingress/controller.go:766	success check health for default cluster
```


```
  	Error Trace:	consumer.go:672
  	            				suite.go:596
  	            				asm_amd64.s:1371
  	Error:      	"{\"message\":\"client request can't be validated\"}\n" does not contain "access key or signature missing"
  	Test:       	suite-features: ApisixConsumer suite-features: scaffold v2 ApisixRoute with hmacAuth consumer
```

https://github.com/apache/apisix-ingress-controller/runs/6749240988?check_suite_focus=true#step:3:2886


```
Summarizing 4 Failures:
[FAIL]suite-features: ApisixConsumer suite-features: scaffold v2 [It] ApisixRoute with hmacAuth consumer
/home/runner/work/apisix-ingress-controller/apisix-ingress-controller/test/e2e/suite-features/consumer.go:672
[FAIL]suite-features: ApisixConsumer suite-features: scaffold v2beta3 [It] ApisixRoute with hmacAuth consumer
/home/runner/work/apisix-ingress-controller/apisix-ingress-controller/test/e2e/suite-features/consumer.go:672
[FAIL]suite-features: ApisixConsumer suite-features: scaffold v2 [It] ApisixRoute with hmacAuth consumer using secret
/home/runner/work/apisix-ingress-controller/apisix-ingress-controller/test/e2e/suite-features/consumer.go:778
[FAIL]suite-features: ApisixConsumer suite-features: scaffold v2beta3 [It] ApisixRoute with hmacAuth consumer using secret
/home/runner/work/apisix-ingress-controller/apisix-ingress-controller/test/e2e/suite-features/consumer.go:778
```

**Comment by tao12345666333** [comment]
```
Error: 2/06/06 08:42:41 [error] 46#46: *2261 [lua] wolf-rbac.lua:151: http_req(): FAIL REQUEST [ {"headers":{"Content-Type":"application\/json; charset=utf-8"},"uri":"http:\/\/172.21.0.1:12180\/wolf\/rbac\/login.rest","body":"{\"authType\":1,\"username\":\"test\",\"appid\":\"test-app\",\"password\":\"test-123456\"}","method":"POST"} ] failed! res is nil, err:timeout, client: 127.0.0.1, server: _, request: "POST /apisix/plugin/wolf-rbac/login HTTP/1.1", host: "localhost:30195"
Error: 2/06/06 08:42:41 [error] 46#46: *2261 [lua] wolf-rbac.lua:385: request_to_wolf_server(): request [{"headers":{"Content-Type":"application\/json; charset=utf-8"},"uri":"http:\/\/172.21.0.1:12180\/wolf\/rbac\/login.rest","body":"{\"authType\":1,\"username\":\"test\",\"appid\":\"test-app\",\"password\":\"test-123456\"}","method":"POST"}] failed! err: timeout, client: 127.0.0.1, server: _, request: "POST /apisix/plugin/wolf-rbac/login HTTP/1.1", host: "localhost:30195"

```

**Comment by tao12345666333** [comment]
```
2022-06-06T09:57:42.5747785Z     2022/06/06 09:57:38 [crit] 48#48: *2083 SSL_do_handshake() failed (SSL: error:1417C0C7:SSL routines:tls_process_client_certificate:peer did not return a certificate) while SSL handshaking, client: 127.0.0.1, server: 0.0.0.0:9443
```

```
2022-06-06T09:57:42.7285099Z     2022-06-06T17:57:23+08:00	[35mdebug[0m	ingress/apisix_route.go:185	translated ApisixRoute	{"routes": [{"id":"db6473e7","name":"ingress-apisix-e2e-tests-default-159513382_httpbin-route_rule1","desc":"Created by apisix-ingress-controller, DO NOT modify it manually","labels":{"managed-by":"apisix-ingress-controller"},"hosts":["mtls.httpbin.local"],"uris":["/*"],"upstream_id":"28a830c7"}], "upstreams": [{"id":"28a830c7","name":"ingress-apisix-e2e-tests-default-159513382_httpbin-service-e2e-test_80","desc":"Created by apisix-ingress-controller, DO NOT modify it manually","labels":{"managed-by":"apisix-ingress-controller"},"type":"roundrobin","nodes":[{"host":"10.244.2.22","port":80,"weight":100}],"scheme":"http"}], "apisix_route": {}, "pluginConfigs": null}
```

**Comment by tao12345666333** [comment]
using #1145 instead. I will close this one.

**Pull request closed without merging**
