### PR TITLE
chore: generate id instead let APISIX do it

### PR DESCRIPTION
**Pull request by tokers**
Please answer these questions before submitting a pull request

- Why submit this pull request?
- [ ] Bugfix
- [x] New feature provided
- [ ] Improve performance
- [ ] Backport patches

Previously, we don't generate resource id, instead, we resort to APISIX to do it, which is not so convenient when we try to get resource from APISIX (we'd have to list all resources in APISIX and find the target by fullname).

Now, we generate resource id from fullname.

### CODE REVIEW

**Comment by tokers** [comment]
@gxthrj

**Comment by gxthrj** [comment]
UT failed

**Comment by tokers** [comment]
@gxthrj Fixed.

**Review by membphis — COMMENTED** [review]
LGTM

**Review by gxthrj — APPROVED** [review]

**Pull request merged**
