### PR TITLE
feat: add support for host pass in upstream crd

### PR DESCRIPTION
**Pull request by ikatlinsky**
### Type of change:

- [x] New feature provided
- [x] Documentation
- [x] CI/CD or Tests

### What this PR does / why we need it:

As per feature request https://github.com/apache/apisix-ingress-controller/issues/1661

### Pre-submission checklist:

- [x] Did you explain what problem does this PR solve? Or what new features have been added?
- [x] Have you added corresponding test cases?
- [x] Have you modified the corresponding document?
- [x] Is this PR backward compatible?

### CODE REVIEW

**Comment by ikatlinsky** [comment]
@tao12345666333 can you please take a look to see if I am moving in the right direction? My changes seem to be ignored by the controller and hostPass is always set to pass.

**Comment by ikatlinsky** [comment]
Will need some time to investigate why e2e tests are failing, I checked them in the _master_ branch and they are also failing quite randomly (examples for external-service.go)

```
Summarizing 3 Failures:
  [FAIL] suite-features: external services update function:  [It] should be able to create the ApisixUpstream later
  /Users/i.katlinsky/go/pkg/mod/github.com/gavv/httpexpect/v2@v2.15.0/reporter.go:24
  [FAIL] suite-features: external services complex usage:  [It] should be able to use backends and upstreams together
  /Users/i.katlinsky/Documents/sandbox/apisix-ingress-controller/test/e2e/suite-features/external-service.go:407
  [FAIL] suite-features: external services complex usage:  [It] should be able to access multiple external services
  /Users/i.katlinsky/go/pkg/mod/github.com/gavv/httpexpect/v2@v2.15.0/reporter.go:24
```

@tao12345666333 is it a known issue?

**Comment by tao12345666333** [comment]
no

**Comment by ikatlinsky** [comment]
here is an example of the failing build on master branch today

https://github.com/apache/apisix-ingress-controller/actions/runs/5491609801

**Comment by tao12345666333** [comment]
let me take a look

**Review by lingsamuel — APPROVED** [review]

**Comment by tao12345666333** [comment]
I will take some time to solve the CI problems. After all test passed, we can merge this one.

**Comment by ikatlinsky** [comment]
nice, make me know when CI problems will be resolved, so i can run test on my side too

**Comment by adam-huganir** [comment]
> let me take a look

I hate to bug you on this @tao12345666333 , but i was wondering if you had any idea when you might have time to take a look at the tests. This is the last feature we need to have purely crd based deployment and we are very excited it is already in the pipeline to deployment. Thanks for all the work so far on this

**Comment by tao12345666333** [comment]
Please merge the master branch first. All test cases be fixed. Thanks

**Comment by ikatlinsky** [comment]
@tao12345666333 merged master into my branch, but at least locally, tests are randomly failing for me with a 504 gateway timeout error. That may not be the case in GitHub actions.

**Comment by ikatlinsky** [comment]
@tao12345666333 as i can see tests on master branch are still failing https://github.com/ikatlinsky/apisix-ingress-controller/actions/runs/5767561884

**Comment by ikatlinsky** [comment]
@tao12345666333 as i see builds on master are still failing https://github.com/apache/apisix-ingress-controller/actions/runs/5767636410

**Comment by tao12345666333** [comment]
@ikatlinsky  Please merge the latest code from the master branch. We have fixed the CI issues.

**Comment by ikatlinsky** [comment]
@tao12345666333 done

**Review by tao12345666333 — APPROVED** [review]
LGTM

**Pull request merged**
