### PR TITLE
feat: ingress annotations support enable websocket

### PR DESCRIPTION
**Pull request by dickens7**
### Type of change:

- [ ] Bugfix
- [x] New feature provided
- [ ] Improve performance
- [ ] Backport patches

### What this PR does / why we need it:

In our daily usage scenarios, we expect to be able to directly open websocket support for routing on ingress

### Pre-submission checklist:

* [x] Did you explain what problem does this PR solve? Or what new features have been added?
* [x] Have you added corresponding test cases?
* [x] Have you modified the corresponding document?
* [x] Is this PR backward compatible? **If it is not backward compatible, please discuss on the [mailing list](https://github.com/apache/apisix-ingress-controller#community) first**

### CODE REVIEW

**Review by tao12345666333 — COMMENTED** [review]
Thanks,

you should add e2e test cases for this one. you can ref to https://github.com/apache/apisix-ingress-controller/blob/master/test/e2e/suite-features/websocket.go 
and add test cases to https://github.com/apache/apisix-ingress-controller/tree/master/test/e2e/suite-annotations directory

**Comment by dickens7** [comment]
> Thanks,
> 
> you should add e2e test cases for this one. you can ref to https://github.com/apache/apisix-ingress-controller/blob/master/test/e2e/suite-features/websocket.go and add test cases to https://github.com/apache/apisix-ingress-controller/tree/master/test/e2e/suite-annotations directory

ok, i'll take a look

**Comment by lingsamuel** [comment]
ci failed

**Comment by tao12345666333** [comment]
Let me take a look

**Comment by AlinsRan** [comment]
> Please help, I have no problem running `make unit-test` locally
> 
> go version go1.18.3 linux/amd64
> 
> Linux seven 5.10.102.1-microsoft-standard-WSL2+ #1 SMP Mon Jun 13 04:56:19 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
> 
> ```
> make unit-test
> go test -cover -coverprofile=coverage.txt ./...
> ?       github.com/apache/apisix-ingress-controller     [no test files]
> ?       github.com/apache/apisix-ingress-controller/cmd [no test files]
> ok      github.com/apache/apisix-ingress-controller/cmd/ingress 10.027s coverage: 80.0% of statements
> ok      github.com/apache/apisix-ingress-controller/pkg/api     0.037s  coverage: 85.7% of statements
> ok      github.com/apache/apisix-ingress-controller/pkg/api/router      0.045s  coverage: 81.8% of statements
> ok      github.com/apache/apisix-ingress-controller/pkg/api/validation  0.050s  coverage: 19.3% of statements
> ok      github.com/apache/apisix-ingress-controller/pkg/apisix  0.366s  coverage: 49.3% of statements
> ok      github.com/apache/apisix-ingress-controller/pkg/apisix/cache    0.010s  coverage: 83.8% of statements
> ok      github.com/apache/apisix-ingress-controller/pkg/config  0.013s  coverage: 64.7% of statements
> ok      github.com/apache/apisix-ingress-controller/pkg/id      0.014s  coverage: 100.0% of statements
> ok      github.com/apache/apisix-ingress-controller/pkg/ingress 0.031s  coverage: 2.1% of statements
> ?       github.com/apache/apisix-ingress-controller/pkg/ingress/gateway [no test files]
> ok      github.com/apache/apisix-ingress-controller/pkg/ingress/gateway/translation     0.226s  coverage: 77.3% of statements
> ?       github.com/apache/apisix-ingress-controller/pkg/ingress/namespace       [no test files]
> ok      github.com/apache/apisix-ingress-controller/pkg/ingress/utils   0.052s  coverage: 37.9% of statements
> ?       github.com/apache/apisix-ingress-controller/pkg/kube    [no test files]
> ?       github.com/apache/apisix-ingress-controller/pkg/kube/apisix/apis/config/v1      [no test files]
> ?       github.com/apache/apisix-ingress-controller/pkg/kube/apisix/apis/config/v2      [no test files]
> ?       github.com/apache/apisix-ingress-controller/pkg/kube/apisix/apis/config/v2beta2 [no test files]
> ?       github.com/apache/apisix-ingress-controller/pkg/kube/apisix/apis/config/v2beta3 [no test files]
> ?       github.com/apache/apisix-ingress-controller/pkg/kube/apisix/client/clientset/versioned  [no test files]
> ?       github.com/apache/apisix-ingress-controller/pkg/kube/apisix/client/clientset/versioned/fake     [no test files]
> ?       github.com/apache/apisix-ingress-controller/pkg/kube/apisix/client/clientset/versioned/scheme   [no test files]
> ?       github.com/apache/apisix-ingress-controller/pkg/kube/apisix/client/clientset/versioned/typed/config/v2  [no test files]
> ?       github.com/apache/apisix-ingress-controller/pkg/kube/apisix/client/clientset/versioned/typed/config/v2/fake     [no test files]
> ?       github.com/apache/apisix-ingress-controller/pkg/kube/apisix/client/clientset/versioned/typed/config/v2beta2     [no test files]
> ?       github.com/apache/apisix-ingress-controller/pkg/kube/apisix/client/clientset/versioned/typed/config/v2beta2/fake        [no test files]
> ?       github.com/apache/apisix-ingress-controller/pkg/kube/apisix/client/clientset/versioned/typed/config/v2beta3     [no test files]
> ?       github.com/apache/apisix-ingress-controller/pkg/kube/apisix/client/clientset/versioned/typed/config/v2beta3/fake        [no test files]
> ?       github.com/apache/apisix-ingress-controller/pkg/kube/apisix/client/informers/externalversions   [no test files]
> ?       github.com/apache/apisix-ingress-controller/pkg/kube/apisix/client/informers/externalversions/config    [no test files]
> ?       github.com/apache/apisix-ingress-controller/pkg/kube/apisix/client/informers/externalversions/config/v2 [no test files]
> ?       github.com/apache/apisix-ingress-controller/pkg/kube/apisix/client/informers/externalversions/config/v2beta2    [no test files]
> ?       github.com/apache/apisix-ingress-controller/pkg/kube/apisix/client/informers/externalversions/config/v2beta3    [no test files]
> ?       github.com/apache/apisix-ingress-controller/pkg/kube/apisix/client/informers/externalversions/internalinterfaces        [no test files]
> ?       github.com/apache/apisix-ingress-controller/pkg/kube/apisix/client/listers/config/v2    [no test files]
> ?       github.com/apache/apisix-ingress-controller/pkg/kube/apisix/client/listers/config/v2beta2       [no test files]
> ?       github.com/apache/apisix-ingress-controller/pkg/kube/apisix/client/listers/config/v2beta3       [no test files]
> ?       github.com/apache/apisix-ingress-controller/pkg/kube/apisix/const       [no test files]
> ok      github.com/apache/apisix-ingress-controller/pkg/kube/translation        1.951s  coverage: 49.7% of statements
> ok      github.com/apache/apisix-ingress-controller/pkg/kube/translation/annotations    0.009s  coverage: 38.8% of statements
> ok      github.com/apache/apisix-ingress-controller/pkg/log     0.021s  coverage: 88.5% of statements
> ok      github.com/apache/apisix-ingress-controller/pkg/metrics 0.028s  coverage: 59.5% of statements
> ok      github.com/apache/apisix-ingress-controller/pkg/types   0.008s  coverage: 87.0% of statements
> ?       github.com/apache/apisix-ingress-controller/pkg/types/apisix/v1 [no test files]
> ok      github.com/apache/apisix-ingress-controller/pkg/version 0.003s  coverage: 100.0% of statements
> ```

You can try to merge the latest code

**Comment by tao12345666333** [comment]
Thanks. 

It's on my list. I will finish review today.

**Review by lingsamuel — APPROVED** [review]

**Review by tao12345666333 — APPROVED** [review]
LGTM

let's move forward.

Thanks!

**Pull request merged**
