### PR TITLE
feat: support ApisixPluginConfig v2

### PR DESCRIPTION
**Pull request by lingsamuel**
Signed-off-by: Ling Samuel <lingsamuelgrace@gmail.com>

### Type of change:
- [x] New feature provided

### CODE REVIEW

**Review by tao12345666333 — APPROVED** [review]
LGTM

**Comment by tao12345666333** [comment]
@lingsamuel please resolve conflicts. thanks

**Comment by lingsamuel** [comment]
@tao12345666333 I solved the conflict in #989 yesterday, let's finish that PR first.

**Comment by tao12345666333** [comment]
hi please resolve the conflics. thanks

**Pull request merged**
