### PR TITLE
chore: introduce ingress-types, rename ApisixTls to ApisixTLS

### PR DESCRIPTION
**Pull request by tokers**
Please answer these questions before submitting a pull request

- Why submit this pull request?
- [ ] Bugfix
- [ ] New feature provided
- [ ] Improve performance
- [ ] Backport patches

- Related issues

___
### Bugfix
- Description

- How to fix?

___
### New feature or improvement
- Describe the details and related test reports.

___
### Backport patches
- Why need to backport?

- Source branch

- Related commits and pull requests

- Target branch

### CODE REVIEW

**Comment by tokers** [comment]
@gxthrj Please take a look when you have time.

**Review by gxthrj — COMMENTED** [review]
Need to update docs which contains `ApisixTls`.

**Comment by tokers** [comment]
> Need to update docs which contains `ApisixTls`.

Ok.

**Comment by gxthrj** [comment]
> > Need to update docs which contains `ApisixTls`.
> 
> The docs are all about CRD `ApisixTls`, considering the compatiblity, i didn't change the CRD name, so no doc need to be updated.

OK

**Review by gxthrj — APPROVED** [review]

**Review by membphis — COMMENTED** [review]
do you have time to look at this PR? it is big PR for me, I can not handle it :(

 @starsz @nic-chen

**Review by starsz — APPROVED** [review]
Also too big for me....

**Pull request merged**
