### PR TITLE
fix: create unique TLS object for each item in Ingress tls

### LINKED ISSUE #1985: bug(ingress/tls): ingress translates TLS keys with several entries to same ApisixTls name; same ID in APISIX
### Current Behavior

When using more than one entry in the `.spec.tls` section of an ingress, the controller will generate multiple ApisixTls intermediate objects via translate:

https://github.com/apache/apisix-ingress-controller/blob/bca0d1da5e0d721ff7c94555821db55dd2659504/pkg/providers/ingress/translation/translator.go#L143-L144

However, these objects do not get a unique name, since they're just using the ingress name and a `-tls` suffix:

https://github.com/apache/apisix-ingress-controller/blob/bca0d1da5e0d721ff7c94555821db55dd2659504/pkg/providers/ingress/translation/translator.go#L90-L93

This leads to these objects all being persisted to APISIX's admin API with the same ID:

https://github.com/apache/apisix-ingress-controller/blob/bca0d1da5e0d721ff7c94555821db55dd2659504/pkg/providers/apisix/translation/apisix_ssl.go#L38-L39

Thus, you only get one entry served in APISIX; others will result in `http_ssl_client_hello_phase` errors in APISIX.

```
2023/09/26 12:46:34 [error] 49#49: *6842565 [lua] init.lua:215: http_ssl_client_hello_phase(): failed to match any SSL certificate by SNI: assets--staging--fun.[snip], context: ssl_client_hello_by_lua*, client: 172.70.243.103, server: 0.0.0.0:9443
```

### Expected Behavior

The ingress controller generates a unique ApisixTls intermediate object, possibly containing the index.

### Error Logs

_No response_

### Steps to Reproduce

Create any ingress with multiple `.spec.tls` entries; observe that only one works.

### Environment

- APISIX Ingress controller version (run `apisix-ingress-controller version --long`) `apache/apisix-ingress-controller:1.7.0`
- Kubernetes cluster version (run `kubectl version`) `1.26.6`
- OS version if running APISIX Ingress controller in a bare-metal environment (run `uname -a`) `N/A`

### PR DESCRIPTION
**Pull request by Revolyssup**
### Type of change:

- [x] Bugfix
- [ ] New feature provided
- [ ] Improve performance
- [ ] Backport patches
- [ ] Documentation
- [ ] Refactor
- [ ] Chore
- [ ] CI/CD or Tests

### What this PR does / why we need it:
Fixes #1985 

### Pre-submission checklist:

- [ ] Did you explain what problem does this PR solve? Or what new features have been added?
- [ ] Have you added corresponding test cases?
- [ ] Have you modified the corresponding document?
- [ ] Is this PR backward compatible? **If it is not backward compatible, please discuss on the [mailing list](https://github.com/apache/apisix-ingress-controller#community) first**

### CODE REVIEW

**Comment by Revolyssup** [comment]
@tao12345666333 Where can I add tests for it? This function doesn't already have a unit test.

**Comment by Revolyssup** [comment]
@acuteaura Were you talking about the safeEncode function, I added that ptal

**Comment by acuteaura** [comment]
I was also thinking about using `DeepHashObject` and `hash/fnv`, purely based on deferred judgement (and performance for fnv should be much better; we have a lot of ingresses). But this is fine too.

**Comment by Revolyssup** [comment]
> Details

Thanks for confirming that the changes work. Once the E2E tests pass, this will be pushed to master. Currently the failing E2E tests might have something to do with the resources available in the github CI environment. I will be fixing this.

**Comment by Sn0rt** [comment]
pls add new test for ensure the compatibility

**Review by Sn0rt — APPROVED** [review]

**Review by AlinsRan — APPROVED** [review]

**Review by shreemaan-abhishek — APPROVED** [review]

**Pull request merged**
