### PR TITLE
docs: added uniform id from apisix-ingress-controller doc

### PR DESCRIPTION
**Pull request by iamayushdas**
Please answer these questions before submitting a pull request

issue: 

- Why submit this pull request?
- [ ] Bugfix
- [ ] New feature provided
- [x] Improve performance
- [ ] Backport patches

- Related issues
https://github.com/apache/apisix-website/issues/363
___
### New feature or improvement
- Describe the details and related test reports.
uniform/particular id given to the documentation

___
### Backport patches
- Why need to backport?

- Source branch

- Related commits and pull requests

- Target branch

### CODE REVIEW

**Review by tao12345666333 — APPROVED** [review]
thanks!

**Comment by gxthrj** [comment]
cc @juzhiyuan PTAL, if you have time.

**Comment by iamayushdas** [comment]
Have a look here - https://github.com/apache/apisix-website/issues/363 

cc @gxthrj

**Comment by juzhiyuan** [comment]
wait for https://github.com/apache/apisix-website/issues/363

**Comment by gxthrj** [comment]
@iamayushdas Now that  https://github.com/apache/apisix-website/issues/363 has been resolved, this PR can be continued.

**Comment by tao12345666333** [comment]
> This PR has to be closed now, as we doesn't meet any final results

This PR has not been updated for too long, I will close it, please feel free to reopen it if necessary.

**Pull request closed without merging**
