### PR TITLE
feat: apisixtls schema

### PR DESCRIPTION
**Pull request by tokers**
Please answer these questions before submitting a pull request

- Why submit this pull request?
- [ ] Bugfix
- [x] New feature provided
- [ ] Improve performance
- [ ] Backport patches

- Related issues

___
### Bugfix
- Description

- How to fix?

___
### New feature or improvement
- Describe the details and related test reports.

___
### Backport patches
- Why need to backport?

- Source branch

- Related commits and pull requests

- Target branch

### CODE REVIEW

**Comment by gxthrj** [comment]
Need some test-case for jsonschema

**Comment by tokers** [comment]
@gxthrj e2e cases about SSL already test it.

**Comment by gxthrj** [comment]
> @gxthrj e2e cases about SSL already test it.

But no error case covered.

**Comment by tokers** [comment]
> > @gxthrj e2e cases about SSL already test it.
> 
> But no error case covered.

That'd will be a huge workload, as we also lacks the cases for ApisixRoute.

**Comment by tokers** [comment]
https://github.com/apache/apisix-ingress-controller/issues/387 I have added an issue to track the test cases.

**Review by gxthrj — APPROVED** [review]

**Pull request merged**
