### PR TITLE
rename command line options and update doc

### PR DESCRIPTION
**Pull request by cmssczy**
fix typo in development.md

### Type of change:

- [x] Bugfix

### What this PR does / why we need it:

fix typo in development.md

### Pre-submission checklist:

* [ ] Did you explain what problem does this PR solve? Or what new features have been added?
* [ ] Have you added corresponding test cases?
* [ ] Have you modified the corresponding document?
* [ ] Is this PR backward compatible? **If it is not backward compatible, please discuss on the [mailing list](https://github.com/apache/apisix-ingress-controller#community) first**

### CODE REVIEW

**Review by tokers — APPROVED** [review]

**Comment by tao12345666333** [comment]
Sorry for delay. Thanks for your contribution.

In fact, after https://github.com/apache/apisix-ingress-controller/pull/826, this configuration item has been removed.

Can you help replace `--apisix-base-url` with `--default-apisix-cluster-base-url`  and `--apisix-admin-key` with `--default-apisix-cluster-admin-key`?

**Comment by cmssczy** [comment]
> Can you help replace `--apisix-base-url` with `--default-apisix-cluster-base-url` and `--apisix-admin-key` with `--default-apisix-cluster-admin-key`?

PTAL. @tao12345666333

**Review by tao12345666333 — APPROVED** [review]
Thanks!

**Comment by tao12345666333** [comment]
After the CI is complete, we can merge it.

**Comment by lijing-21** [comment]
Hi @cmssczy, thank you for your contribution!

Here is the Contributor T-shirt form[1], if you're interested, kindly take a look :)

[1] https://github.com/apache/apisix/blob/master/CONTRIBUTING.md#contributor-t-shirt

**Pull request merged**
