### PR TITLE
chore: migrate chart to repo apisix-helm-charts

### PR DESCRIPTION
**Pull request by Junnplus**
- Related issues
https://github.com/apache/apisix-ingress-controller/issues/256

### CODE REVIEW

**Comment by tokers** [comment]
@Junnplus Will merge https://github.com/apache/apisix-helm-chart/pull/31 firstly and publish a chart to the repository first, then we need to update the prerequisites for docs in `docs/deployments` (just use the repo).

**Comment by Junnplus** [comment]
> then we need to update the prerequisites for docs in docs/deployments (just use the repo).

Good. That couldn't be better.

**Comment by tokers** [comment]
@Junnplus Please merge the newest master branch when you have time, the CI failure was fixed.

**Comment by tokers** [comment]
> @Junnplus Please merge the newest master branch when you have time, the CI failure was fixed.

Any updates?

**Review by gxthrj — APPROVED** [review]

**Pull request merged**
