### PR TITLE
refactor: remove BaseURL and AdminKey in config

### PR DESCRIPTION
**Pull request by zaunist**
### Type of change:

- [ ] Bugfix
- [ ] New feature provided
- [x] Improve performance
- [ ] Backport patches

### What this PR does / why we need it:

Remove BaseURL and AdminKey.

### Pre-submission checklist:

* [x] Did you explain what problem does this PR solve? Or what new features have been added?
* [x] Have you added corresponding test cases?
* [ ] Have you modified the corresponding document?
* [x] Is this PR backward compatible? **If it is not backward compatible, please discuss on the [mailing list](https://github.com/apache/apisix-ingress-controller#community) first**

### CODE REVIEW

**Review by tokers — APPROVED** [review]
This is a broken change and we should add some hints for users.

**Review by tao12345666333 — APPROVED** [review]
LGTM.

**Comment by tao12345666333** [comment]
Thanks! The code LGTM. 

I added the `do-not-merge/hold` label, and I want to perform additional checks and remind more people to pay attention to this change.

Will be merged after the bi-weekly meeting next week.

**Comment by zaunist** [comment]
> This is a broken change and we should add some hints for users.

Sure, I think so.

**Review by starsz — APPROVED** [review]

**Review by tao12345666333 — APPROVED** [review]
LGTM

**Pull request merged**
