### PR TITLE
feat: add support for Endpointslices

### PR DESCRIPTION
**Pull request by lianghao208**
Please answer these questions before submitting a pull request

- Why submit this pull request?
- [ ] Bugfix
- [X] New feature provided
- [ ] Improve performance
- [ ] Backport patches

- Related issues

#201

### CODE REVIEW

**Comment by lianghao208** [comment]
@tokers PTAL, thanks! btw, why isn't there any checks running in this PR?

**Comment by tokers** [comment]
@lianghao208 Thanks for your contribution, that's really cool!

Some e2e cases should be added to verify this PR, also, i have added some comments on this PR.

**Comment by lianghao208** [comment]
@tokers Ok, I will check the comments.

**Comment by lianghao208** [comment]
@tokers 
I think in istio, they use bool type `EnableEndpointSliceController` from env params when running the controller:
[https://github.com/istio/istio/blob/f41b17563d0ae00a99694cb1a73e329c4a09ff3d/pilot/pkg/features/pilot.go#L224-#L230](https://github.com/istio/istio/blob/f41b17563d0ae00a99694cb1a73e329c4a09ff3d/pilot/pkg/features/pilot.go#L224-#L230)
 and then convert it into struct `Option` with string "endpointsOnly" or "endpointsliceOnly".
But apisix ingress controller import read configuration from file or configMap, wouldn't it be redundant if using string like "endpointsOnly" or "endpointsliceOnly" in configuration file?  any suggestions?

**Comment by membphis** [comment]
@lianghao208 Please merge the master branch and fix the conflicting files. 
image

**Comment by lianghao208** [comment]
@membphis done, already solved the confilcts

**Comment by tokers** [comment]
@lianghao208 For now, endpoints controller itself has a couple of problems need to be fixed (See #218 ), maybe it has to wait for a while.

**Comment by lianghao208** [comment]
hold until the reconstruct of Apisix CRD is finished.

**Comment by gxthrj** [comment]
@lianghao208 there are some conflicting files :)

**Comment by lianghao208** [comment]
@gxthrj 
Yes, I am waiting for the reconstruction of ApisixUpstream CRD ( involving some files related to endpoints), once it's finished by tokers, I will resolved the conflict files.

**Comment by tokers** [comment]
@lianghao208 I think this PR now can be went ahead.

**Comment by tokers** [comment]
> @lianghao208 I think this PR now can be went ahead.

You can refer to the endpoints controller :).

**Comment by membphis** [comment]
@lianghao208 need you to resolve the conflict files

image

**Pull request closed without merging**
