### PR TITLE
fix:  add namespace for the ServiceAccount reference in ClusterRoleBinding

### PR DESCRIPTION
**Pull request by gxthrj**

### CODE REVIEW

**Comment by tao12345666333** [comment]
I think it is unnecessary.

**Comment by tokers** [comment]
Title is confusing.

**Comment by gxthrj** [comment]
It will got error if there is no namespace here.

**Review by tao12345666333 — APPROVED** [review]

**Comment by tao12345666333** [comment]
Because the kind we used here is `ServiceAccount` which is in the namespace scope, the namespace field must be specified here. If we are using `User` or `Group`, we don't need it.

**Review by tokers — APPROVED** [review]

**Review by starsz — APPROVED** [review]

**Review by nic-chen — APPROVED** [review]

**Pull request merged**
